trigger:
  branches:
    include:
    - master
    - greenkeeper/*
pr:
  branches:
    include:
    - '*'
    # must quote since "*" is a YAML reserved character; we want a string

stages:
  - stage: Build the Extension
    jobs:
    - job: OS_and_Platform
      strategy:
        matrix:
          linux_node_10:
            imageName: Hosted Ubuntu 1604
            node_version: 10.x
          linux_node_12:
            imageName: Hosted Ubuntu 1604
            node_version: 12.x
          mac_node_10:
            imageName: Hosted macOS
            node_version: 10.x
          mac_node_12:
            imageName: Hosted macOS
            node_version: 12.x
          windows_node_10:
            imageName: Hosted VS2017
            node_version: 10.x
          windows_node_12:
            imageName: Hosted VS2017
            node_version: 12.x
      pool:
        name: $(imageName)
      # pool:
        # https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops&tabs=yaml#use-a-microsoft-hosted-agent
        # name: Hosted Ubuntu 1604
        demands: npm

      steps:
      - template: .azure-pipelines/build.yml
      - template: .azure-pipelines/lint.yml
      - template: .azure-pipelines/test.yml
      - template: .azure-pipelines/package.yml

    # - job: Windows
    #   pool:
    #     name: Hosted VS2017
    #     demands: npm
    #   strategy:
    #     matrix:
    #       node_10_x:
    #         node_version: 10.x
    #       node_12_x:
    #         node_version: 12.x
    #   steps:
    #   - template: .azure-pipelines/build.yml
    #   - template: .azure-pipelines/lint.yml
    #   - template: .azure-pipelines/test.yml

    # - job: macOS
    #   pool:
    #     name: Hosted macOS
    #     demands: npm
    #   strategy:
    #     matrix:
    #       node_10_x:
    #         node_version: 10.x
    #       node_12_x:
    #         node_version: 12.x
    #   steps:
    #   - template: .azure-pipelines/build.yml
    #   - template: .azure-pipelines/lint.yml
    #   - template: .azure-pipelines/test.yml

