steps:
  # Archive files
  # Compress files into .7z, .tar.gz, or .zip
  - task: ArchiveFiles@2
    displayName: 'Create Docs Pipeline Artifact'
    inputs:
      rootFolderOrFile: '$(Build.SourcesDirectory)/docs/.vuepress/dist'
      includeRootFolder: false
      archiveType: 'zip' # Options: zip, 7z, tar, wim
      #tarCompression: 'gz' # Optional. Options: gz, bz2, xz, none
      archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
      replaceExistingArchive: true
      #verbose: # Optional
      #quiet: # Optional
    condition: succeeded()

  # - task: PublishPipelineArtifact@0
  #   displayName: 'Publish Docs Pipeline Artifact'
  #   inputs:
  #     targetPath: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
  #   condition: succeeded()

  # Publish build artifacts
  # Publish build artifacts to Azure Pipelines or a Windows file share
  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
      artifactName: 'MyDocsOutput'
      #publishLocation: 'Container' # Options: container, filePath
      #targetPath: # Required when publishLocation == FilePath
      #parallel: false # Optional
      #parallelCount: # Optional
    condition: succeeded()
